// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {libretranslate} from '../models';

export function GetFrontendSettings():Promise<libretranslate.FrontendSettings>;

export function GetLanguages():Promise<Array<libretranslate.Language>>;

export function Translate(arg1:libretranslate.TranslateRequest):Promise<libretranslate.TranslateResponse>;
