// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLanguages() {
  return window['go']['libretranslate']['Service']['GetLanguages']();
}

export function Translate(arg1) {
  return window['go']['libretranslate']['Service']['Translate'](arg1);
}
