// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings() {
  return window['go']['settings']['Service']['GetSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['settings']['Service']['SaveSettings'](arg1);
}

export function Snapshot() {
  return window['go']['settings']['Service']['Snapshot']();
}
