// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';

export function GetSettings():Promise<settings.Settings>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;

export function Snapshot():Promise<string>;

export function UpdateSettings(arg1:Record<string, any>):Promise<settings.Settings>;
